-- CREATE TABLE `books`(
--     `book_index` int(5) UNSIGNED NOT NULL COMMENT 'Book Index',
--     `book_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Book Id',
--     `title` varchar(200)  NOT NULL COMMENT 'Book Title',
--     `author` varchar(100)  NULL COMMENT 'Author',
--     `description` varchar(1000)  NULL COMMENT 'Description',
--     `availability` boolean NOT NULL DEFAULT 1 COMMENT 'Book availability',
--     `image_url` varchar(200) NULL COMMENT 'Image url',
--     `reg_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Time added'
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Book table';

-- TRUNCATE TABLE `books`;

-- ALTER TABLE `books`
--   ADD PRIMARY KEY (`book_index`),
--   ADD UNIQUE KEY (`book_id`);

-- ALTER TABLE `books`
--   MODIFY `book_index` int(5) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Book Index';

CREATE TABLE `my_library`.`books` (
  `book_index` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Book Index' ,  
  `book_id` VARCHAR(100) NOT NULL COMMENT 'Book ID' ,  
  `title` VARCHAR(200) NOT NULL COMMENT 'Title' ,  
  `author` VARCHAR(100) NOT NULL COMMENT 'Author' ,  
  `description` VARCHAR(2000) NOT NULL COMMENT 'Description' ,  
  `availability` INT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Number of books available' ,
  `category` VARCHAR(20) NOT NULL COMMENT 'Book Category' ,  
  `rating` DECIMAL(2, 1) NOT NULL COMMENT 'Book Rating' ,
  `image_url` VARCHAR(200) NOT NULL COMMENT 'Image url' ,  
  `publisher_id` VARCHAR(100) NOT NULL COMMENT 'Publisher ID' ,
  `published_year` INT(4) NOT NULL COMMENT 'Published Year' ,
  `online_reading_url` VARCHAR(200) NULL COMMENT 'Online reading url' ,
  `physical_location` VARCHAR(10) NOT NULL COMMENT 'Floor Rack Row' ,
  `no_of_times` INT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'No of times borrows' ,  
  `reg_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Registered time' ,    
  PRIMARY KEY  (`book_index`),    UNIQUE  (`book_id`)
) ENGINE = InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT = 'Book Table';

-- Example Insert Query

INSERT INTO `books` (`book_index`, `book_id`, `title`, `author`, `description`, `availability`, `category`, `rating`, `image_url`, `publisher_id`, `published_year`, `online_reading_url`, `physical_location`, `no_of_times`, `reg_time`) VALUES (NULL, 'book001', 'The Ivory Tower and Harry Potter', 'Lana A. Whited', 'Now available in paper, The Ivory Tower and Harry Potter is the first book-length analysis of J. K. Rowling\'s work from a broad range of perspectives within literature, folklore, psychology, sociology, and popular culture. A significant portion of the book explores the Harry Potter series\' literary ancestors, including magic and fantasy works by Ursula K. LeGuin, Monica Furlong, Jill Murphy, and others, as well as previous works about the British boarding school experience. Other chapters explore the moral and ethical dimensions of Harry\'s world, including objections to the series raised within some religious circles. In her new epilogue, Lana A. Whited brings this volume up to date by covering Rowling\'s latest book, Harry Potter and the Order of the Phoenix.', '5', 'Literary', '4.5', 'http://books.google.com/books/content?id=iO5pApw2JycC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'pub001', '2004', 'http://play.google.com/books/reader?id=iO5pApw2JycC&hl=&printsec=frontcover&source=gbs_api', '5 1 1', '0', CURRENT_TIMESTAMP);
INSERT INTO `books` (`book_index`, `book_id`, `title`, `author`, `description`, `availability`, `category`, `rating`, `image_url`, `publisher_id`, `published_year`, `online_reading_url`, `physical_location`, `no_of_times`, `reg_time`) VALUES (NULL, 'book002', 'Harry Potter and the Philosopher\'s Stone', 'J.K. Rowling', 'Turning the envelope over, his hand trembling, Harry saw a purple wax seal bearing a coat of arms; a lion, an eagle, a badger and a snake surrounding a large letter \'H\'.\\\" Harry Potter has never even heard of Hogwarts when the letters start dropping on the doormat at number four, Privet Drive. Addressed in green ink on yellowish parchment with a purple seal, they are swiftly confiscated by his grisly aunt and uncle. Then, on Harry\'s eleventh birthday, a great beetle-eyed giant of a man called Rubeus Hagrid bursts in with some astonishing news: Harry Potter is a wizard, and he has a place at Hogwarts School of Witchcraft and Wizardry. An incredible adventure is about to begin! Pottermore has now launched the Wizarding World Book Club. Visit Pottermore to sign up and join weekly Twitter discussions at WW Book Club.', '3', 'Fiction', '4.5', 'http://books.google.com/books/content?id=39iYWTb6n6cC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'pub002', '2015', 'http://play.google.com/books/reader?id=39iYWTb6n6cC&hl=&printsec=frontcover&source=gbs_api', '4 1 1', '0', CURRENT_TIMESTAMP);
INSERT INTO `books` (`book_index`, `book_id`, `title`, `author`, `description`, `availability`, `category`, `rating`, `image_url`, `publisher_id`, `published_year`, `online_reading_url`, `physical_location`, `no_of_times`, `reg_time`) VALUES (NULL, 'book003', 'Deep Learning', 'Ian Goodfellow', 'An introduction to a broad range of topics in deep learning, covering mathematical and conceptual background, deep learning techniques used in industry, and research perspectives.', '1', 'Computers', '3.0', 'http://books.google.com/books/content?id=Np9SDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api2', 'pub003', '2016', 'http://play.google.com/books/reader?id=Np9SDQAAQBAJ&hl=&printsec=frontcover&source=gbs_api', '2 1 1', '0', CURRENT_TIMESTAMP);
INSERT INTO `books` (`book_index`, `book_id`, `title`, `author`, `description`, `availability`, `category`, `rating`, `image_url`, `publisher_id`, `published_year`, `online_reading_url`, `physical_location`, `no_of_times`, `reg_time`) VALUES (NULL, 'book004', 'Fundamentals of Deep Learning', 'Nikhil Buduma', 'With the reinvigoration of neural networks in the 2000s, deep learning has become an extremely active area of research, one that’s paving the way for modern machine learning. In this practical book, author Nikhil Buduma provides examples and clear explanations to guide you through major concepts of this complicated field. Companies such as Google, Microsoft, and Facebook are actively growing in-house deep-learning teams. For the rest of us, however, deep learning is still a pretty complex and difficult subject to grasp. If you’re familiar with Python, and have a background in calculus, along with a basic understanding of machine learning, this book will get you started. Examine the foundations of machine learning and neural networks Learn how to train feed-forward neural networks Use TensorFlow to implement your first neural network Manage problems that arise as you begin to make networks deeper Build neural networks that analyze complex images Perform effective dimensionality reduction using autoencoders Dive deep into sequence analysis to examine language Learn the fundamentals of reinforcement learning', '5', 'Computers', '5.0', 'http://books.google.com/books/content?id=n0IlDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'pub004', '2017', 'http://play.google.com/books/reader?id=n0IlDwAAQBAJ&hl=&printsec=frontcover&source=gbs_api', '2 1 2', '0', CURRENT_TIMESTAMP);
INSERT INTO `books` (`book_index`, `book_id`, `title`, `author`, `description`, `availability`, `category`, `rating`, `image_url`, `publisher_id`, `published_year`, `online_reading_url`, `physical_location`, `no_of_times`, `reg_time`) VALUES (NULL, 'book005', 'Being Successful as an Engineer', 'William H. Roadstrum', 'This text is designed to help the young engineer make the transition from student to practicing professional. It provides experience-based suggestions and helpful warnings to guide new engineers in taking the first steps to successful project leadership and group management.', '2', 'Business', '2.0', 'http://books.google.com/books/content?id=EvONfO8C4ZYC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'pub005', '2004', 'http://play.google.com/books/reader?id=EvONfO8C4ZYC&hl=&printsec=frontcover&source=gbs_api', '3 1 1', '0', CURRENT_TIMESTAMP);
INSERT INTO `books` (`book_index`, `book_id`, `title`, `author`, `description`, `availability`, `category`, `rating`, `image_url`, `publisher_id`, `published_year`, `online_reading_url`, `physical_location`, `no_of_times`, `reg_time`) VALUES (NULL, 'book006', 'Hold Paramount: The Engineer’s Responsibility to Society', 'Alastair Gunn', 'This essential text provides students with practical insight into the engineering code of ethics and how a practicing engineer is obligated to act in a responsible manner. To illustrate the complexities involved with acting in an ethical fashion, the authors have created characters that encounter a number of situations that test the engineering code of ethics. The dialogue between these characters highlights different perspectives of realistic situations that students will face as practicing engineers. As they proceed through the book, students see how the code can help in decision making, as well as the implications of various decisions. The philosophical theory that supports the ethical positions encountered is presented as boxed material following each section. Important Notice: Media content referenced within the product description or the product text may not be available in the ebook version.', '3', 'Engineering', '4.9', 'http://books.google.com/books/content?id=kA_Rh46LbOQC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'pub006', '2010', 'http://books.google.com.my/books?id=kA_Rh46LbOQC&printsec=frontcover&dq=%7Bengineer%7D&hl=&cd=2&source=gbs_api', '3 1 2', '0', CURRENT_TIMESTAMP);
INSERT INTO `books` (`book_index`, `book_id`, `title`, `author`, `description`, `availability`, `category`, `rating`, `image_url`, `publisher_id`, `published_year`, `online_reading_url`, `physical_location`, `no_of_times`, `reg_time`) VALUES (NULL, 'book007', 'Rosie Revere, Engineer', 'Andrea Beaty', 'Rosie may seem quiet during the day, but at night she’s a brilliant inventor of gizmos and gadgets who dreams of becoming a great engineer. When her great-great-aunt Rose (Rosie the Riveter) comes for a visit and mentions her one unfinished goal—to fly—Rosie sets to work building a contraption to make her aunt’s dream come true. But when her contraption doesn’t fly but rather hovers for a moment and then crashes, Rosie deems the invention a failure. On the contrary, Aunt Rose insists that Rosie’s contraption was a raging success: you can only truly fail, she explains, if you quit. From the powerhouse author-illustrator team of Iggy Peck, Architect comes Rosie Revere, Engineer, another charming, witty picture book about believing in yourself and pursuing your passion. Praise for Rosie Revere, Engineer\\\"Comically detailed mixed-media illustrations that keep the mood light and emphasize Rosie’s creativity at every turn.\\\"—Publishers Weekly \\\"The detritus of Rosie’s collections is fascinating, from broken dolls and stuffed animals to nails, tools, pencils, old lamps and possibly an erector set. And cheddar-cheese spray.\\\" —Kirkus Reviews \\\"This celebration of creativity and perseverance is told through rhyming text, which gives momentum and steady pacing to a story, consistent with the celebration of its heroine, Rosie. She’s an imaginative thinker who hides her light under a bushel (well, really, the bed) after being laughed at for one of her inventions.\\\" —Booklist Award 2013 Parents\' Choice Award - GOLD 2014 Amelia Bloomer Project List ReadBoston\'s Best Read Aloud Book', '4', 'Fiction', '4.5', 'http://books.google.com/books/content?id=cRDwBwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'pub007', '2013', 'http://books.google.com.my/books?id=cRDwBwAAQBAJ&printsec=frontcover&dq=%7Bengineer%7D&hl=&cd=5&source=gbs_api', '4 1 2', '0', CURRENT_TIMESTAMP);
INSERT INTO `books` (`book_index`, `book_id`, `title`, `author`, `description`, `availability`, `category`, `rating`, `image_url`, `publisher_id`, `published_year`, `online_reading_url`, `physical_location`, `no_of_times`, `reg_time`) VALUES (NULL, 'book008', 'From Engineer to Manager', 'B. Michael Aucoin', 'If you are looking for a lively, down-to-earth experience in the journey to innovative engineering management, this is definitely the book for you. The author\'s 20-plus year perspective indicates that, while most engineers will spend the majority of their careers as managers, most are dissatisfied with the transition. Much of this frustration is the result of lack of preparation and training. This book gives you a solid grounding in the critical attitudes and principles needed for success.', '9', 'Business', '4', 'http://books.google.com/books/content?id=Sgtq6224kfEC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'pub009', '2002', 'http://books.google.com.my/books?id=Sgtq6224kfEC&printsec=frontcover&dq=%7Bengineer%7D&hl=&cd=5&source=gbs_api', '1 1 1', '0', CURRENT_TIMESTAMP);
INSERT INTO `books` (`book_index`, `book_id`, `title`, `author`, `description`, `availability`, `category`, `rating`, `image_url`, `publisher_id`, `published_year`, `online_reading_url`, `physical_location`, `no_of_times`, `reg_time`) VALUES (NULL, 'book009', 'Electrical Engineer\'s Reference Book', 'M. A. Laughton', 'For ease of use, this edition has been divided into the following subject sections: general principles; materials and processes; control, power electronics and drives; environment; power generation; transmission and distribution; power systems; sectors of electricity use. New chapters and major revisions include: industrial instrumentation; digital control systems; programmable controllers; electronic power conversion; environmental control; hazardous area technology; electromagnetic compatibility; alternative energy sources; alternating current generators; electromagnetic transients; power system planning; reactive power plant and FACTS controllers; electricity economics and trading; power quality. *An essential source of techniques, data and principles for all practising electrical engineers *Written by an international team of experts from engineering companies and universities *Includes a major new section on control systems, PLCs and microprocessors', '3', 'Engineering', '3.5', 'http://books.google.com/books/content?id=5jOblzV5eZ8C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'pub010', '2002', 'http://books.google.com.my/books?id=5jOblzV5eZ8C&printsec=frontcover&dq=%7Bengineer%7D&hl=&cd=8&source=gbs_api', '3 1 3', '0', CURRENT_TIMESTAMP);
INSERT INTO `books` (`book_index`, `book_id`, `title`, `author`, `description`, `availability`, `category`, `rating`, `image_url`, `publisher_id`, `published_year`, `online_reading_url`, `physical_location`, `no_of_times`, `reg_time`) VALUES (NULL, 'book010', 'The Halo Effect', 'Phil Rosenzweig', 'Controversial and iconoclastic, a veteran corporate manager and business school professor exposes the dangerous myths, fantasies, and delusions that pervade much of the business world today.', '2', 'Business', '4', 'http://books.google.com/books/content?id=hJHHAwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'pub008', '2014', 'http://books.google.com.my/books?id=hJHHAwAAQBAJ&printsec=frontcover&dq=%7Bbusiness%7D&hl=&cd=1&source=gbs_api', '1 1 3', '0', CURRENT_TIMESTAMP);
INSERT INTO `books` (`book_index`, `book_id`, `title`, `author`, `description`, `availability`, `category`, `rating`, `image_url`, `publisher_id`, `published_year`, `online_reading_url`, `physical_location`, `no_of_times`, `reg_time`) VALUES (NULL, 'book011', 'Business for Higher Awards', 'Dave Needham', 'This student text offers full coverage of the core units for Business HNC/D, reinforcing the theory with case studies and activities to develop students\' knowledge and understanding.', '2', 'Business', '3.4', 'http://books.google.com/books/content?id=8w3hXLIBfywC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'pub011', '1999', 'http://books.google.com.my/books?id=8w3hXLIBfywC&printsec=frontcover&dq=%7Bbusiness%7D&hl=&cd=2&source=gbs_api', '1 1 4', '0', CURRENT_TIMESTAMP);
INSERT INTO `books` (`book_index`, `book_id`, `title`, `author`, `description`, `availability`, `category`, `rating`, `image_url`, `publisher_id`, `published_year`, `online_reading_url`, `physical_location`, `no_of_times`, `reg_time`) VALUES (NULL, 'book012', 'Business to Business Marketing Management', 'Jim Blythe', 'This pioneering new text covers current theories on business-to-business marketing from a global standpoint. It covers current theory from a practical viewpoint and includes market entry strategies trade fairs, reputation management and corporate communications. It looks at selling and marketing between organisations, companies, This pioneering new text covers current theories on business-to-business marketing from a global standpoint. It covers current theory from a practical viewpoint and includes market entry strategies trade fairs, reputation management and corporate communications. It looks at selling and marketing between organisations, companies,', '4', 'Business', '4.2', 'http://books.google.com/books/content?id=KvJJfj3BF-YC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'pub006', '2005', 'http://books.google.com.my/books?id=KvJJfj3BF-YC&printsec=frontcover&dq=%7Bbusiness%7D&hl=&cd=3&source=gbs_api', '1 1 5', '0', CURRENT_TIMESTAMP);
INSERT INTO `books` (`book_index`, `book_id`, `title`, `author`, `description`, `availability`, `category`, `rating`, `image_url`, `publisher_id`, `published_year`, `online_reading_url`, `physical_location`, `no_of_times`, `reg_time`) VALUES (NULL, 'book013', 'Business Policy and Strategic Managemen', '\"G. V. Satya Sekhart', 'The knowledge of business policy and techniques of strategic management is the need of the hour to prospective business managers. The present competitive environment has brought several drastic changes in policy making and strategic management. Hence, there is necessity of theoretical understanding about the business policy as well as strategic management. Most of the organizations have started adopting strategic management system. This book focuses on conceptual approach to the subject as well as some select case studies, which make a foundation to the knowledge of strategic management.', '0', 'Business', '3.5', 'http://books.google.com/books/content?id=nYNPtZNnx9YC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'pub014', '2009', 'http://books.google.com.my/books?id=nYNPtZNnx9YC&printsec=frontcover&dq=%7Bbusiness%7D&hl=&cd=4&source=gbs_api', '1 1 5', '0', CURRENT_TIMESTAMP);
INSERT INTO `books` (`book_index`, `book_id`, `title`, `author`, `description`, `availability`, `category`, `rating`, `image_url`, `publisher_id`, `published_year`, `online_reading_url`, `physical_location`, `no_of_times`, `reg_time`) VALUES (NULL, 'book014', 'Applying Psychology in Business', 'John Walter Jone', 'To learn more about Rowman & Littlefield titles please visit us at www.rowmanlittlefield.com', '1', 'Business', '2.3', 'http://books.google.com/books/content?id=8Qvx21qA9gcC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'pub013', '1991', 'http://books.google.com.my/books?id=8Qvx21qA9gcC&printsec=frontcover&dq=%7Bbusiness%7D&hl=&cd=7&source=gbs_api', '1 1 6', '0', CURRENT_TIMESTAMP);
INSERT INTO `books` (`book_index`, `book_id`, `title`, `author`, `description`, `availability`, `category`, `rating`, `image_url`, `publisher_id`, `published_year`, `online_reading_url`, `physical_location`, `no_of_times`, `reg_time`) VALUES (NULL, 'book015', 'The Computer Music Tutorial', 'Curtis Roads', 'This text provides a step-by-step introduction to the entire field of computer music techniques. Written for nontechnical as well as technical readers, it uses hundreds of charts, diagrams, screen images, and photographs as well as clear explanations to present basic concepts and terms.', '2', 'Computers', '4.3', 'http://books.google.com/books/content?id=nZ-TetwzVcIC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'pub003', '1996', 'http://books.google.com.my/books?id=nZ-TetwzVcIC&printsec=frontcover&dq=%7Bcomputer%7D&hl=&cd=4&source=gbs_api', '2 1 3', '0', CURRENT_TIMESTAMP);
INSERT INTO `books` (`book_index`, `book_id`, `title`, `author`, `description`, `availability`, `category`, `rating`, `image_url`, `publisher_id`, `published_year`, `online_reading_url`, `physical_location`, `no_of_times`, `reg_time`) VALUES (NULL, 'book016', 'Computer Simulation of Liquids', 'M. P. Allen', 'This book describes how to use computers to simulate the properties of liquids. It provides an introduction and practical guide to the molecular dynamics and Monte Carlo methods. \'The book is comprehensive, thorough and readable\' Chemistry in Britai', '2', 'Computers', '3.8', 'http://books.google.com/books/content?id=O32VXB9e5P4C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'pub015', '1989', 'http://books.google.com.my/books?id=O32VXB9e5P4C&printsec=frontcover&dq=%7Bcomputer%7D&hl=&cd=5&source=gbs_api', '2 1 4', '0', CURRENT_TIMESTAMP);
INSERT INTO `books` (`book_index`, `book_id`, `title`, `author`, `description`, `availability`, `category`, `rating`, `image_url`, `publisher_id`, `published_year`, `online_reading_url`, `physical_location`, `no_of_times`, `reg_time`) VALUES (NULL, 'book017', 'Computer Graphics', 'James D. Foley', 'A guide to the concepts and applications of computer graphics covers such topics as interaction techniques, dialogue design, and user interface software.', '3', 'Computers', '3.6', 'http://books.google.com/books/content?id=-4ngT05gmAQC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'pub017', '1996', 'http://books.google.com.my/books?id=-4ngT05gmAQC&printsec=frontcover&dq=%7Bcomputer%7D&hl=&cd=6&source=gbs_api', '2 1 5', '0', CURRENT_TIMESTAMP);
INSERT INTO `books` (`book_index`, `book_id`, `title`, `author`, `description`, `availability`, `category`, `rating`, `image_url`, `publisher_id`, `published_year`, `online_reading_url`, `physical_location`, `no_of_times`, `reg_time`) VALUES (NULL, 'book018', 'Multimedia', 'Tony Feldman', 'First Published in 1993. Routledge is an imprint of Taylor & Francis, an informa company.', '2', 'Computers', '3.7', 'http://books.google.com/books/content?id=O__G_uZWSk0C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'pub018', '1994', 'http://books.google.com.my/books?id=O__G_uZWSk0C&printsec=frontcover&dq=%7Bmultimedia%7D&hl=&cd=2&source=gbs_api', '2 1 6', '0', CURRENT_TIMESTAMP);
INSERT INTO `books` (`book_index`, `book_id`, `title`, `author`, `description`, `availability`, `category`, `rating`, `image_url`, `publisher_id`, `published_year`, `online_reading_url`, `physical_location`, `no_of_times`, `reg_time`) VALUES (NULL, 'book019', 'Drawing for Engineering', 'Paul Smith', 'Based on the South African Bureau of Standards Code of Practice for Engineering Drawing (SABS 0111),this book is a step-by-step guide to drawing techniques. It teaches both technical drawing and freehand sketching, and has special units with applications for mechanical and chemical engineering.', '0', 'Engineering', '3.8', 'http://books.google.com/books/content?id=b1C4AvkOs9AC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'pub019', '1999', 'http://books.google.com.my/books?id=b1C4AvkOs9AC&printsec=frontcover&dq=%7Bengineering%7D&hl=&cd=7&source=gbs_api', '3 1 4', '0', CURRENT_TIMESTAMP);
INSERT INTO `books` (`book_index`, `book_id`, `title`, `author`, `description`, `availability`, `category`, `rating`, `image_url`, `publisher_id`, `published_year`, `online_reading_url`, `physical_location`, `no_of_times`, `reg_time`) VALUES (NULL, 'book020', 'Usability Engineering', 'Jakob Nielsen', 'Executive Summary. What is usability. Generations of user interfaces. The usability engineering lifecycle. Usability heuristics. Usability testing. Usability assessment methods beyond testing. Interface standards. International user interfaces. Future developments. Exercises. Bibliography. Author index. Subject index.', '3', 'Engineering', '4.1', 'http://books.google.com/books/content?id=95As2OF67f0C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'pub020', '1994', 'http://books.google.com.my/books?id=95As2OF67f0C&printsec=frontcover&dq=%7Bengineering%7D&hl=&cd=9&source=gbs_api', '3 1 5', '0', CURRENT_TIMESTAMP);







